### ISSUE TITLE
Create share for tests data

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais-testing#12]
df = get_data(wd_filename = f'file:///user/dcr/data/edr3_WDs.csv', ....

Relying on a file in a user's home directory makes the test very fragile.

How large is the data ?

Can we create a shared directory test data and put a copy of it there?

**Comment by stvoutsin** [comment]
Yes I agree, I think we need to setup a shared directory for the test data. That particular file is around 630Mb.
Do you want to set up the shared directory or should I? If the second, do you have notes on how you've done it for the other data shares?

**Comment by stvoutsin** [comment]
Fixed in recent commit on aglais github repo: https://github.com/wfau/aglais/commit/4b71198a193aa5ccaade02d77c0cf049defe7d6e
